### PR TITLE
manual-zmq: Updated an installation manual for zmq

### PR DESCRIPTION
**Pull request by Antarus66**
Updated an installation manual for zmq

### CODE REVIEW

**Comment by m1x0n** [comment]
Could you please remove steps where you describe how to work in vim? Thanks.

**Comment by m1x0n** [comment]
Also it would be nice to have it in english

**Comment by m1x0n** [comment]
In part of this scope we can also translate the main README.

**Comment by Antarus66** [comment]
Ok,  I'll translate it.

**Pull request merged**
